sudo: required
services:
  - docker
before_install:
  - docker build -t satyambaran/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true satyambaran/docker-react npm run test

  # docker run cont_id npm run test -- --coverage